[build]
command = "npm install"  # No build step, just install dependencies
functions = "functions"
publish = "public"  # Ensure static files (CSS, images) are served

[build.environment]
NODE_VERSION = "22.14.0"

[dev]
command = "node app.js"  # Start the Express server locally
port = 8888
targetPort = 3000

[functions]
directory = "functions"
