[build]
command = "npm install"
publish = "public"  # Only if you have static files

[build.environment]
NODE_VERSION = "20.18.1"  # Match your package.json version

[functions]
directory = "functions"
node_bundler = "esbuild"

[dev]
command = "netlify dev"
port = 8888
targetPort = 3000
