[build]
command = "npm install"  # Install dependencies
publish = "public"  # Only needed if you have static assets

[build.environment]
NODE_VERSION = "22.14.0"

[dev]
command = "netlify dev"  # Start local Netlify Functions server
port = 8888
targetPort = 3000

[functions]
directory = "functions"  # This is where Netlify looks for functions
node_bundler = "esbuild"  # Faster bundling for functions
